### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by alekksander** [kaputnikGo/LittleSirEcho#1] opened 2017-01-08 15:42 UTC
app doesnt work on adroid 5.1

**Comment by kaputnikGo** [comment] 2017-01-08 21:09
Do you have any more information about the device it doesn't work on and more specifics as to what happens when you try to run it?

**Comment by alekksander** [comment] 2017-01-09 13:44
Unmodified (i believe) android 5.1 inside cat s40. 
It starts with the phone, says it's enabled from now on, but no matter if i'm on „vibrate”, or regular mode, it doesn't do anything with unread messages. My default app for messages is QKSMS.

**Comment by kaputnikGo** [comment] 2017-01-09 20:58
I think the issue is to do with the package name of QKSMS. I will update this repo and the google play store version within the next 24 hours.

**Comment by kaputnikGo** [comment] 2017-01-09 22:00
Updated this repo and Google Play store (version 4 (2.2)) which hopefully solves the package name issue.

**Comment by alekksander** [comment] 2017-01-10 08:46
is there an apk around? i'm not friends with google ;)

**Comment by kaputnikGo** [comment] 2017-01-10 08:54
ha ha, me neither. there is one here in the repo, in the /bin folder of the source.

**Comment by alekksander** [comment] 2017-01-10 13:42
sorry to inform, but still not working :(

**Comment by kaputnikGo** [comment] 2017-01-10 21:36
ok, well it would seem this needs more investigating. This app is simple in that it listens for notifications that are posted by packages containing the name "sms" or "mms" and then posts its own notification. It doesn't listen to the actual sms app. It also requires explicit permission from the user to allow this app to listen to notifications. This can all be a bit flakey on android - https://code.google.com/p/android/issues/detail?id=62811

but you can try this:
* Rebooting
* Going back in to "Notification access" and disabling and re-enabling the app

I will keep looking into it.

**Comment by alekksander** [comment] 2017-01-11 11:17
Is it normal that every time i go to the app it doesn't remember that i set it to 30seconds (default 10 minutes is selected) and shows up toast message saying „Little Sir Echo enabled”?

**Comment by kaputnikGo** [comment] 2017-01-11 12:23
That sounds like the app is being force closed by the OS. It should appear as a running process and a service for the notification listener. I've just updated the apk here to include a method in the notification listener that may help. If it doesn't then i think the problem could be how the OS interacts with a background service.  I will have a look for some CAT s40 info if i can find any.

**Comment by kaputnikGo** [comment] 2017-01-11 12:33
The s40 appears to have an app called Clean-Master installed as stock - this may be interfering as the Clean-Master app has a notification cleaner and memory optimiser.

**Comment by alekksander** [comment] 2017-01-11 12:51
first thing i did (months ago) was disabling those cleaners, and other stuff that i don't trust (including google play). i also do not use any other software like that (mem optimizers, task killers etc).
update didn't help… there is still no Little Sir Echo service running. Is there other notification app i could try to see if its OS or app itself?

**Comment by kaputnikGo** [comment] 2017-01-11 21:48
The settings get saved in the app's shared preferences location, so it sounds like the app is getting force closed somehow.
This repo:
https://github.com/kpbird/NotificationListenerService-Example
has an apk that you could try, it offers similar functions for the listener part.

To debug you could plug your phone into a computer running adb etc. I use eclipse with adb for this.  For use and testing i have two phones running cyanogenmod, one with gapps, one without.

**Comment by alekksander** [comment] 2017-01-12 12:12
okay i installed NLS-E, but what exactly should i do with it now in order to test notifications?

**Comment by kaputnikGo** [comment] 2017-01-12 21:33
thats for you to figure out, try and see if it works.

**Comment by alekksander** [comment] 2017-01-13 01:53
Okay so the service is on and seem to be working 
![tmp_29122-screenshot_2017-01-13-02-48-55-587902412](https://cloud.githubusercontent.com/assets/3148302/21915621/6a480d20-d93b-11e6-9448-d8e019a17346.png)

**Comment by alekksander** [comment] 2017-01-13 01:58
Perhaps LSE  is crashing before the data is saved?

**Comment by kaputnikGo** [comment] 2017-01-13 10:21
That app works in that way but does it receive notifications from your sms app? And leave it running in the background for some time.

**Comment by alekksander** [comment] 2017-01-13 10:28
seems to be fully working:
![screenshot_2017-01-13-11-26-15](https://cloud.githubusercontent.com/assets/3148302/21926743/5ab1f2b6-d983-11e6-96a7-51345a4d3388.png)

![screenshot_2017-01-13-11-27-30](https://cloud.githubusercontent.com/assets/3148302/21926744/5ecb825e-d983-11e6-8201-d22d3a845777.png)

![screenshot_2017-01-13-11-27-43](https://cloud.githubusercontent.com/assets/3148302/21926747/60e4c726-d983-11e6-935e-4cadc96e9232.png)

**Comment by kaputnikGo** [comment] 2017-01-18 23:32
ok, thats good information to have. this will require a bit more time to analyse however.

**Comment by kaputnikGo** [comment] 2017-01-19 00:33
Mostly the code in the NLSExample app is similar enough to LittleSirEcho. Two major differences are that LSE requires the permissions  WAKE_LOCK (to trigger the repeat notification after a period of time) and RECEIVE_BOOT_COMPLETED (to allow the app to restart after a reboot of the phone as per a user's request). From what you have said above it seems like LSE is not running correctly at all which may mean there is a permissions problem.

**Comment by alekksander** [comment] 2017-02-03 11:30
the news is, that after phone restart the service is running (but has no effect so far). it disappears from list of services after i launch app from icon.

**Comment by kaputnikGo** [comment] 2017-02-15 02:43
Sorry about the delay, it would seem that your phone is shutting it down for reasons as yet determined.  Its explicit in requiring permissions and also needs notification read access, something that has been known to be problematic in some android versions. Unless you can get a logcat report then I'm afraid I can't help. The app is working fine for other users AFAIK.

**Closed** 2020-06-03 17:05 UTC
